---
- name: Creating backups directory
  file: dest={{backups_dir}} state=directory owner={{backups_user}} group={{backups_group}}
  become: yes

- name: Copying files to {{backups_dir}}
  template: src="{{item}}" dest="{{backups_dir}}/{{item}}"
            owner={{backups_user}} group={{backups_group}} mode=u+x
  with_items:
    - backup-lib.sh

- name: Create backup scripts
  include_role:
    name: backup_script
  with_items:
    - { backup_type: 'github', backup_min_size: "{{ 22 * 1024 * 1024 }}" }
  vars:
    backup_type: "{{item.backup_type}}"
    script_content: "{{lookup('template', './templates/{{item.backup_type}}-backup.sh')}}"
    backup_min_size: "{{item.backup_min_size}}"