homeassistant_dir: "/opt/homeassistant"
homeassistant_venv: "{{homeassistant_dir}}/.venv"
homeassistant_port: 8123
homeassistant_version: 0.54.0
homeassistant_user: "{{ansible_ssh_user}}"
homeassistant_group: "{{ansible_ssh_user}}"

homeassistant_general_config:
  name: MyHome
  latitude: 52.3702
  longitude: 4.8952
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam

nest_client_id: "nest_client_id"
nest_client_secret: "nest_client_secret"
nest_access_token: "nest_access_token"

roofcam_ip: "{{ansible_default_ipv4.address}}"
roofcam_port: 1234

phue_ip: 10.0.0.1
phue_username: "phue_username"

atv_host: 10.0.0.2
atv_login_id: "atv_login_id"

samsungtv_host: 10.0.0.3

nmap_tracker_hosts: 10.0.0.0/24
