- name: Starting selenium docker container
  docker_container:
    name: "{{selenium_container_name}}"
    image: "{{selenium_docker_image}}"
    state: started # Modify and restart iff config has changed
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host
    recreate: "{{recreate_containers}}"
    restart_policy: unless-stopped
  become: yes
  tags:
    - selenium-container

- name: Install casa-container for selenium (aliases only for now)
  include_role:
    name: casa-container
  vars:
    alias_shorthand: "selenium"
    container_name: "{{selenium_container_name}}"

- name: Creating casa-tests casa-service
  include_role:
    name: casa-service
  vars:
    service_name: "casa-tests"
  become: yes

- name: Copy over casa-tests files
  copy:
    src: ../../tests/
    dest: "{{casa_tests_dir}}"
    owner: "casa-tests"
    group: "casa-tests"
  become: yes

- name: "Creating casa-tests-sanity.sh"
  template: src="casa-tests-sanity.sh" dest="{{casa_tests_dir}}/casa-tests-sanity.sh"
            owner=casa-tests group=casa-tests mode=u=rwx,o=rx
  become: yes

- name: Build casa-tests container
  docker_image:
    path: "{{casa_tests_dir}}"
    name: casa-tests
    force: yes
  become: yes

- name: Modifying sudoers file so casa-tests user can run casa-tests docker container
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'casa-tests ALL=({{item.user}}) NOPASSWD: {{item.command}}'
    validate: visudo -cf %s
  become: yes
  with_items:
    - {"user": "root", "command": "/usr/bin/docker run casa-tests *"}

# Run casa-tests every 5 min
- name: "Adding cronjob for  script"
  cron: name="Periodic casa-tests sanity run" minute="*/5" job="{{casa_tests_dir}}/casa-tests-sanity.sh"
        user=casa-tests
  become: yes
