backups_dir: "/opt/backups"
backups_user: "{{ansible_ssh_user}}"
backups_group: "{{backups_user}}"

backups_monitoring_dir: "{{backups_dir}}/monitoring"

github_backups_dir: "{{backups_dir}}/github"
github_username: "foobar"
