- name: daemon_reload
  command: systemctl daemon-reload
  become: yes

- name: restart_sonos_http_api
  service: name={{sonos_http_api_service}}@{{sonos_http_api_user}} state=restarted
  become: yes
  notify: wait_for_sonos_api_port

- name: wait_for_sonos_api_port
  wait_for:
    host: 0.0.0.0
    port: "{{sonos_http_api_port}}"
