grafana_docker_image: "grafana/grafana:5.3.4"

grafana_user: "grafana"
grafana_group: "{{grafana_user}}"
grafana_uid: 472 # Needs to be 472 to work with docker: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
grafana_conf_dir: "/etc/grafana"
grafana_log_dir: "/var/log/grafana"

grafana_service: "grafana-server"
grafana_bind_ip: "0.0.0.0"
grafana_port: 3001

grafana_admin_user: "admin"
grafana_admin_password: "pass123"

grafana_backups_dir: "{{backups_dir}}/grafana"
grafana_backups_venv: "{{grafana_backups_dir}}/.venv"
grafana_backups_api_token: "mytoken"
