#########################################################################
# Grouping of light sources                                             #
#########################################################################

lights_downstairs:
  name: "Downstairs lights"
  view: no
  entities:
   - light.woonkamer_tv
   - light.tv_staanlamp
   - light.living_room
   - light.office_ambience
   - light.eetkamer
   - light.kitchen
   - light.kantoor
   - switch.desk_lamp

lights_outside:
  name: "Lights outside"
  view: no
  entities:
    - light.voordeur
    - light.garden