#########################################################################
# Grouping of light sources                                             #
#########################################################################

lights_downstairs:
  name: "Downstairs lights"
  view: no
  entities:
   - light.woonkamer_tv
   - light.tv_staanlamp
   - light.living_room
   - light.dining_table
   - light.kitchen
   - light.office
   - switch.desk_lamp
   - switch.christmas_tree
   - switch.christmas_ambience_office

lights_downstairs_automatic:
  name: "Automatically controlled downstairs lights"
  view: no
  entities:
    - light.living_ambience_lamp_1

lights_outside:
  name: "Lights outside"
  view: no
  entities:
    - light.lamp_voordeur_1
    - light.garden

lights_christmas:
  name: "Christmas lights"
  view: no
  entities:
    - switch.christmas_tree
    - switch.christmas_ambience_office