#####################################################
# House Scenes                                      #
#####################################################
- name: Sleeping
  entities:
    light.woonkamer_tv:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    light.eettafel:
        state: off
    light.kitchen:
        state: off
    group.light_office:
        state: off
    media_player.bathroom:
        state: paused
    input_select.downstairs_music:
        option: NoMusic

# 'Home' really just needs to turn off the diepvries cam which happens through an automation
# However, HomeAssistant doesn't like empty entity dicts in scenes
- name: Home
  entities:
    light.eettafel:
        state: off

- name: Away
  entities:
    light.woonkamer_tv:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    light.eettafel:
        state: off
    light.kitchen:
        state: off
    group.light_office:
        state: off
    media_player.bathroom:
        state: paused
    input_select.downstairs_music:
        option: NoMusic

###################################
# Living scenes                  #
###################################

- name: Watching TV
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: NoMusic

- name: Breakfast
  entities:
    light.woonkamer_tv:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    light.eettafel:
        state: on
    light.kitchen:
        state: off
    group.light_office:
        state: off
    input_select.downstairs_music:
        option: Breakfast

- name: Romance
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    group.light_office:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Romance

- name: Christmas
  entities:
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Christmas

- name: Relaxing
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    group.light_office:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Relaxing

- name: Reading
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 255
    light.living_room:
        state: off
    light.kitchen:
        state: off

- name: NoPreset
  entities:
    media_player.living_room:
        state: paused
    media_player.tv_room:
        state: paused

#####################################
# Downstairs Modifier scenes        #
#####################################

- name: Cooking
  entities:
    light.living_room:
        state: off
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.kitchen:
        state: on

###########################################
# Bathroom scenes                         #
###########################################

- name: Bathroom Morning Ritual
  entities:
    light.garden:
        state: off

- name: Relaxing Shower
  entities:
    light.garden:
        state: off


###########################################
# Misc                                    #
###########################################

- name: Good Morning
  entities:
    light.garden:
        state: off

- name: Start Work Day
  entities:
    light.garden:
        state: off
    group.light_office:
        state: on
    media_player.bathroom:
        state: paused