#####################################################
# House Scenes                                      #
#####################################################
- name: Sleeping
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    group.light_dinner_table:
        state: off
    light.kitchen:
        state: off
    group.light_office:
        state: off
    group.light_front_door:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: NoMusic
    input_boolean.cooking:
        option: off

# 'Home' really just needs to turn off the diepvries cam which happens through an automation
# However, HomeAssistant doesn't like empty entity dicts in scenes
- name: Home
  entities:
    group.light_dinner_table:
        state: off

- name: Away
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    group.light_dinner_table:
        state: off
    light.kitchen:
        state: off
    group.light_office:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: NoMusic
    input_boolean.cooking:
        option: off

###################################
# Living scenes                  #
###################################

- name: Watching TV
  entities:
    light.woonkamer_tv:
        state: on
        kelvin": 2200
        brightness_pct: 40
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: NoMusic

- name: Breakfast
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    group.light_dinner_table:
        state: on
    light.kitchen:
        state: off
    group.light_office:
        state: off
    input_select.downstairs_music:
        option: Breakfast

- name: Romance
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    group.light_office:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Romance

- name: Christmas
  entities:
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Christmas

- name: Relaxing
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    group.light_office:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Relaxing

- name: Reading
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 255
    light.living_room:
        state: off
    light.kitchen:
        state: off

- name: NoPreset
  entities:
    media_player.living_room:
        state: paused
    media_player.tv_room:
        state: paused

- name: OutdoorLightsOn
  entities:
    group.light_front_door:
        state: on
    light.garden:
        state: on

- name: OutdoorLightsOff
  entities:
    group.light_front_door:
        state: off
    light.garden:
        state: off

##################
# Cooking        #
##################

- name: Cooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: on

- name: StopCooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: off

############
# Mornings #
############
- name: StartWorkDay
  entities:
    light.garden:
        state: off
    group.light_front_door:
        state: off
    group.light_office:
        state: on
    light.nachttafel_joris:
        state: off
    input_select.bathroom_music:
        option: NoMusic

- name: BathroomMorningWeekDay
  entities:
    input_select.bathroom_music:
        option: Bathroom Morning
