################################################################################
# House Scenes                                                                 #
################################################################################
- name: Sleeping
  entities:
    group.lights_outside:
        state: off
    group.lights_downstairs:
        state: off
    group.lights_downstairs_automatic:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_select.camera_preset:
        option: All On
    input_boolean.cooking:
        state: off

- name: Home
  entities:
    input_select.camera_preset:
        option: Home

# When away, don't turn off lights_downstairs_automatic or group.lights_outside
# These are controlled automatically for security reasons
- name: Away
  entities:
    group.lights_downstairs:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_boolean.cooking:
        state: off
    input_select.camera_preset:
        option: All On

################################################################################
# Living Scenes                                                                #
################################################################################

- name: Watching TV
  entities:
    light.woonkamer_tv:
        state: on
        kelvin: 2200
        brightness_pct: 40
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.camera_preset:
        option: Home

- name: StopWatchingTV
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    input_select.living_preset:
        option: NoPreset

- name: Breakfast
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    light.eetkamer:
        state: on
    light.kitchen:
        state: off
    light.kantoor:
        state: off
    input_select.downstairs_music:
        option: Breakfast
    input_select.camera_preset:
        option: Home

- name: Romance
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.kantoor:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Romance
    input_select.camera_preset:
        option: Home

- name: Christmas
  entities:
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Christmas
    input_select.camera_preset:
        option: Home
    switch.christmas_tree:
        state: on
    switch.christmas_ambience_office:
        state: on

- name: Relaxing
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.kantoor:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Relaxing
    input_select.camera_preset:
        option: Home

- name: Reading
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 255
    light.living_room:
        state: off
    light.kitchen:
        state: off
    input_select.camera_preset:
        option: Home

- name: NoPreset
  entities:
    media_player.living_room:
        state: paused
    media_player.tv_room:
        state: paused

################################################################################
# Cooking                                                                      #
################################################################################

- name: Cooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: on
    input_select.camera_preset:
        option: Home
    input_boolean.cooking:
        state: on

- name: StopCooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: off
    input_boolean.cooking:
        state: off

################################################################################
# Mornings                                                                     #
################################################################################
- name: StartWeekDay
  entities:
    group.lights_outside:
        state: off
    light.kantoor:
        state: on
    light.nachttafel_joris:
        state: off
    light.kitchen:
        state: on
    input_select.bathroom_music:
        option: "Bathroom NoMusic"
    input_select.downstairs_music:
        option: Pop
    switch.desk_lamp:
        state: on
    input_select.camera_preset:
        option: Home
    light.bathroom_group:
        state: off

- name: BathroomMorningWeekDay
  entities:
    input_select.bathroom_music:
        option: Bathroom Morning
    light.bathroom_group:
        state: on

################################################################################
# Evenings                                                                     #
################################################################################

- name: Sunset
  entities:
    group.lights_outside:
        state: on
    light.living_ambience_lamp_1:
        state: on
        kelvin: 2200
        brightness_pct: 20
        # Apparently brightness_pct doesn't work on a light group, hence why this is living_ambience_lamp_1
        # and not kantoor_sfeer_verlichting
    switch.christmas_tree:
        state: on
    switch.christmas_ambience_office:
        state: on

- name: Midnight
  entities:
    group.lights_outside:
        state: off

- name: ComeHomeEvening
  entities:
    group.lights_outside:
        state: on
    light.living_ambience_lamp_1:
        state: on
        kelvin: 2200
        brightness_pct: 20
        # Apparently brightness_pct doesn't work on a light group, hence why this is living_ambience_lamp_1
        # and not kantoor_sfeer_verlichting
    light.woonkamer_tv:
        state: on
        kelvin: 2200
        brightness_pct: 40
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20

################################################################################
# Working                                                                      #
################################################################################

- name: StartWorkingMorning
  entities:
    input_select.downstairs_music:
        option: NoMusic
    light.kitchen:
        state: off

- name: Working
  entities:
    light.kantoor:
        state: on
    switch.desk_lamp:
        state: on
    input_select.camera_preset:
        option: Home

- name: NotWorking
  entities:
    switch.desk_lamp:
        state: off

################################################################################
# Bathroom                                                                     #
################################################################################
- name: BathroomEnter
  entities:
    light.bathroom_group:
        state: on
    switch.bathroom_mirror:
        state: on

- name: BathroomLeave
  entities:
    input_select.bathroom_music:
        option: "Bathroom NoMusic"
    light.bathroom_group:
        state: off
    switch.bathroom_mirror:
        state: off

- name: RelaxingShower
  entities:
    input_select.bathroom_music:
        option: "Bathroom Relaxing"