################################################################################
# Hallway Mode                                                                 #
################################################################################
- alias: Hallway Time of Day
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.hallway
      to: "on"
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "{% raw %}scene.Hallway{{ states('input_select.house_mode')}}{% endraw %}"

- alias: Toilet Time of Day
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.wc_beneden_lamp_1
      to: "on"
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "{% raw %}scene.Toilet{{ states('input_select.house_mode')}}{% endraw %}"