route:
  receiver: 'slack-receiver'

  # How long to initially wait to send a notification for a group
  # of alerts. Allows to wait for an inhibiting alert to arrive or collect
  # more initial alerts for the same group. (Usually ~0s to few minutes.)
  group_wait: 30s

  # How long to wait before sending a notification about new alerts that
  # are added to a group of alerts for which an initial notification has
  # already been sent. (Usually ~5m or more.)
  group_interval: 5m

  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert. (Usually ~3h or more).
  repeat_interval: 1h
  group_by: [cluster, alertname]

receivers:
  - name: "slack-receiver"
    slack_configs:
      - channel: "{{slack_default_channel}}"
        username: "{{slack_username}}"
        api_url: "{{slack_home_room_webhook}}"
        text: "Sonos API down"