groups:
- name: sonos-api
  rules:
    - alert: sonos-http-api.systemd
      expr: "node_systemd_unit_state{name=~'{{sonos_http_api_service}}(.*)', state='active'} == 0"
      for: 30s
      labels:
        severity: page
      annotations:
        summary: "sonos API down"
    - alert: sonos-http-api.http
      expr: "probe_success{name='sonos-http-api.http'} == 0"
      for: 30s
      labels:
        severity: page

- name: ELK
  rules:
    - alert: elk-logstash.systemd
      expr: "node_systemd_unit_state{name=~'{{logstash_service}}(.*)', state='active'} == 0"
      for: 30s
      labels:
        severity: page
    # - alert: elk-es.http
    #   expr: "probe_success{name='elk-es.http'} == 0"
    #   for: 30s
    #   labels:
    #     severity: page
    - alert: elk-kibana.http
      expr: "probe_success{name='elk-kibana.http'} == 0"
      for: 30s
      labels:
        severity: page

- name: Hubs
  rules:
    - alert: hue.hub
      expr: "probe_success{name='hue.icmp'} == 0"
      for: 30s
      labels:
        severity: page
    - alert: tradfri.hub
      expr: "probe_success{name='tradfri.icmp'} == 0"
      for: 30s
      labels:
        severity: page

- name: Homeassistant
  rules:
    - alert: hadash.http
      expr: "probe_success{name='hadash.http'} == 0"
      for: 30s
      labels:
        severity: page
    - alert: homeassistant.http
      expr: "probe_success{name='homeassistant.http'} == 0"
      for: 30s
      labels:
        severity: page

- name: Google
  rules:
    - alert: google.http
      expr: "probe_success{name='google.http'} == 0"
      for: 30s
      labels:
        severity: page

- name: Backups
  rules:
    - alert: backups
      expr: "custom_backup_check_status > 0"
      for: 30s
      labels:
        severity: page

- name: Sanity Tests
  rules:
    - alert: tests-sanity.status
      expr: "casa_tests_status > 0"
      for: 30s
      labels:
        severity: page

- name: InfluxDB
  rules:
    - alert: influxdb.systemd
      expr: "node_systemd_unit_state{name=~'{{influxdb_service}}(.*)', state='active'} == 0"
      for: 30s
      labels:
        severity: page

- name: Node Exporter
  rules:
    - alert: node_exporter.up
      expr: "up{job='Node Exporter'} == 0"
      for: 30s
      labels:
        severity: page
